# Generated by Django 2.2.2 on 2019-11-17 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='收藏主题名称')),
                ('ishot', models.BooleanField(verbose_name='是否推荐')),
                ('icon', models.CharField(max_length=30, verbose_name='图标名称')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookmark.Topic', verbose_name='父主题')),
            ],
            options={
                'db_table': 'bookmark_topic',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='链接名称')),
                ('info', models.CharField(max_length=100, verbose_name='链接简介')),
                ('url', models.CharField(max_length=100, verbose_name='链接URL')),
                ('pic', models.ImageField(height_field=120, upload_to='bookmarkimg/', verbose_name='链接配图', width_field=120)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmark.Topic', verbose_name='链接所属主题')),
            ],
            options={
                'db_table': 'bookmark_link',
            },
        ),
    ]
