# Generated by Django 2.2.2 on 2019-11-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_auto_20191117_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='pic',
            field=models.ImageField(upload_to='bookmarkimg/', verbose_name='链接配图'),
        ),
    ]
