# Generated by Django 2.2.2 on 2019-08-06 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('brief', models.CharField(max_length=200, verbose_name='文件简介')),
                ('body', models.TextField(verbose_name='文章内容')),
                ('avatar', models.ImageField(blank=True, upload_to='article/%Y%m%d/', verbose_name='文章配图')),
                ('viewnum', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blog_article',
                'ordering': ['-created'],
            },
        ),
    ]
