# Generated by Django 2.2.2 on 2019-12-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='网站名称')),
                ('logo', models.ImageField(upload_to='config/', verbose_name='网站Logo')),
                ('copyright', models.CharField(blank=True, max_length=30, verbose_name='CopyRight文字')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='网站标题')),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='网站关键字')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='网站描述')),
                ('linklogo', models.ImageField(upload_to='config/', verbose_name='搜藏夹网站Logo')),
            ],
            options={
                'verbose_name': '网站基本信息',
                'verbose_name_plural': '网站基本信息',
                'db_table': 'blog_config',
            },
        ),
    ]
